### ISSUE TITLE
'Create a named item' snippet throws error when running more than once

### ISSUE THREAD

**Issue by Rickyp** [OfficeDev/office-js-snippets#210]
![image](https://user-images.githubusercontent.com/7102621/46174602-598e1c00-c25e-11e8-9fbc-7c21ac1516e0.png)

**Comment by AlexJerabek** [comment]
Thanks for reporting this @Rickyp. I'll work up a fix soon and share the results on this thread.

**Comment by AlexJerabek** [comment]
Hi @Rickyp,
A couple things. One, I couldn't get this to repo on "Create a named item", but I did see this behavior on the other Named Item snippets.
Second, I'm wondering if this is desirable behavior and would appreciate your input. The role of snippets is to show how the code acts. Is it valuable to know referencing a non-existent NamedItem throws an error? Or is it better to show how to check if NamedItems exist (and avoiding the error)?

**Comment by AlexJerabek** [comment]
Hi @Rickyp 

The snippet has been updated to warn of this behavior, while preserving the simplicity of the code sample. The sample about updating named items shows how to check if the named item already exists.

I'm going to close the issue. Please reopen it if you notice any other problems. Thanks!
