### ISSUE TITLE
Modify "gradients" sample to make use of setCellProperties

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-js-snippets#318]
I've seen two questions on StackOverflow about getting or setting cell properties in bulk, the most recent of which was yesterday:  https://stackoverflow.com/questions/56755657/how-does-the-range-function-getcellproperties-in-the-javascript-excel-api-work.

The “Just for Fun -> Gradient” sample would be trivially convertible to make use of the setCellProperties API, and would run an order of magnitude faster than it does today (or faster still on larger sizes).

You could even make it be two different helper functions, that are redirected to based on whether `isSetSupported("ExcelApi", 1.9)` is true.

I'm happy to review the PR.
- Michael

**Comment by AlexJerabek** [comment]
Thanks @Zlatkovsky. We'll look into improving that sample and writing a separate one that'll be more searchable. [Internal task link](https://office.visualstudio.com/OC/_workitems/edit/3455984).

**Comment by AlexJerabek** [comment]
Fixed with #320. Closing this issue.
