### ISSUE TITLE
onSelectionChanged event - sample request

### ISSUE THREAD

**Issue by frantwo** [OfficeDev/office-js-snippets#453]
I have not idea if here it is the correct site, but I would like to know if onSelectionChanged event still is in BETA version or already is available. I would like to use it but I don't find any example.
BR!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18b63cfd-c1ea-baed-f96f-b14664b384c5
* Version Independent ID: 52aaa0e2-be99-c2e7-3042-fb652420613e
* Content: [Word.ContentControl class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/word/word/word.contentcontrol.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.contentcontrol.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@AlexJerabek Please reassign if you're not the right person.

**Comment by Rick-Kirkham** [comment]
@frantwo The preview events and event handling in Word are known to be buggy, so we don't have a sample. See if you can use the events in the Common APIs: [Detect changes ...](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/bind-to-regions-in-a-document-or-spreadsheet#detect-changes-to-data-or-the-selection-in-a-binding)
