### ISSUE TITLE
Pivot Table Samples are broken

### ISSUE THREAD

**Issue by kudlur** [OfficeDev/office-js-snippets#460]
### Bug Report

- **Host**: Excel
- **OS**: Windows 10
- **Browser**: N/A
- **Environment**: PROD

#### Expected behavior:

In Desktop Version of Excel, running Pivot Table Samples should work

#### Actual behavior:

The steps where Pivot Table APIs are invoked, the samples crash with the following error
Rich API Error. AccessDenied. You cannot perform the requested Operation.

Please note:, there is absolutely no issue when the samples are run in Web version of Excel

#### Steps to Reproduce:

1. Run Desktop version of Excel
2. Launch ScriptLab Add-in
3. Click on "Samples" and enter "Pivot" in Search box
4. Click on "Create and Modify" Sample to run it
5. From the "Run" menu, click on "Run In this Pane"
6. Click on "Setup Sample" button
7.Next click on "Create" button. This results in the AccessDenied error logged to the Console

#### Failure Logs:

c {name: "RichApi.Error", code: "AccessDenied", traceMessages: Array[0], innerError: null, debugInfo: Object}
 name: "RichApi.Error"
 code: "AccessDenied"
 traceMessages: Array[0]
 innerError: null
▶debugInfo: Object
 code: "AccessDenied"
 message: "You cannot perform the requested operation."
 toString: function ()
 errorLocation: "PivotTableCollection.add"
 statement: "var add=pivotTables.add(...);"
▶surroundingStatements: Array[9]
 0: "..."
 1: "var worksheet1=worksheets.getItem(...);"
 2: "var range1=worksheet1.getRange(...);"
 3: "// Instantiate {range1}"
 4: "var worksheet2=worksheets.getItem(...);"
 5: "var pivotTables=worksheet2.pivotTables;"
 6: "// >>>>>"
 7: "var add=pivotTables.add(...);"
 8: "// <<<<<"
▶fullStatements: Array[1]

![image](https://user-images.githubusercontent.com/6069411/84965375-c43f5500-b0dc-11ea-8ff1-608054456a0a.png)

**Comment by Rick-Kirkham** [comment]
I can't reproduce this. The Pivot table snippets all work fine for me.

**Comment by AlexJerabek** [comment]
Hi @kudlur, 
I'm encountering the same failures as you when using Excel on Desktop. As a temporary workaround, are you able to run the PivotTable snippets on Excel for the web?

**Comment by kudlur** [comment]
Hi @AlexJerabek 

No problem running PivotTable Snippets (all of them) on Excel for the Web.

Also the snippets work on Desktop version of excel, if i called any range operations that modify the range, right before any PivotTable operations
For Ex: 

context.workbook.getSelectedRange().format.autofitRows(); 
context.workbook.pivotTables.refreshAll()
context.sync();

**Comment by AlexJerabek** [comment]
Thanks for checking @kudlur. I'm glad you can view and use the samples in some capacity. 

I'm working with the product team to investigate the issue and find out the problem. In the meantime, based on @Rick-Kirkham's report, it's likely you'll no longer encounter the issue once your version of Excel is updated. If that does turn out to be the case, please report that to this thread.

**Comment by kudlur** [comment]
Thanks @AlexJerabek for the reply.

I am having this issues on a project that I am working for the client.  
I used the Script-Lab samples to highlight that same issue, so it is easier for anyone to reproduce it.

I also have my personal machine with Excel Version 2005 (Build: 12920.20336,  Click-To-Run), and even there, this issue exists.

For now, I am calling  range modification function as a work-around, before refreshing PivotTables.
Waiting to here about the fox though. 
Thanks

**Comment by kudlur** [comment]
Also, forgot to mention, that this issue cropped up few days back. Before that, I had no issues with the PivotTable related functions.

**Comment by AlexJerabek** [comment]
Hi @kudlur, 
I've spoken to the product team. They believe is was something broken in the office-js layer that should be fixed now. You may need to [clear the Office cache](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache) to get the latest bits. Please let me know if that helps.

**Comment by kudlur** [comment]
Thank You @AlexJerabek and the office team
Cleared the Office Cache, and tested my app without the workaround. Looks like the issue is resolved.
Also, all pivot table samples on Script-Lab work without any issues.
