### ISSUE TITLE
JS Office Outlook  add-in: get email as a file

### ISSUE THREAD

**Issue by yanikkoval** [OfficeDev/office-js-snippets#48]
Hello, 

Maybe it's irrelevant for these snippets set, but is it possible to get **whole email as a file or just collect all email data** using office javascript package? I didn't find any similar method in reference:
https://dev.office.com/reference/add-ins/outlook/1.5/Office?product=outlook&version=v1.5 
But it is possible to get all email data (body, cc, etc.) one by one, is it the only way? 

I know it is possible to do so using Microsoft Exchange and email id and access token, but I can't share access tokens due to security requirements. 

Thank you!

**Comment by Rick-Kirkham** [comment]
@yanikkoval 
Thanks for your interest. Technical questions like this should be raised on StackOverflow. Be sure and tag the question "office-js".
