### ISSUE TITLE
PowerPoint Shapes API preview bug when working with multiple shapes

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/office-js-snippets#618]
This issue occurs in PowerPoint when running the "Insert shape, line, and text box" sample in Script lab. Sample code is here: https://github.com/OfficeDev/office-js-snippets/blob/main/samples/powerpoint/preview-apis/shapes.yaml

If you are on a slide with multiple shapes the code can get confused when shrinking or moving the hexagon. It can end up grabbing a different element and applying incorrect settings. Need to ensure it can correctly identity and use the hexagon.

Repo steps:
1. Open PowerPoint on desktop and a new presentation. You will get a blank slide with title and subtitle.
2. Open Script lab and run the sample.
3. Choose "Create hexagon".
4. Choose "Shrink hexagon". At this point the title will get shrunk, not the hexagon.
5. Choose "Move hexagon". Again the title is moved, but not the hexagon.

**Comment by Rick-Kirkham** [comment]
A step was left out of the instructions. (Users should delete all existing shapes before pressing any of the other buttons.)
