### ISSUE TITLE
Bug in Find text matches within a range

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js-snippets#623]
It appears the example has a bug, it always searches for “Groceries”, whatever value one enters in the text-box.

If I change this:

    searchRange.find($("#searchText").text(), {

to

    searchRange.find($("#searchText").val().toString(), {

the example works as expected.

**Comment by AlexJerabek** [comment]
Thank you for reporting this issue, @jkpieterse. Just to confirm, this is in the "Find text matches within a range" sample for Excel, correct?

**Comment by alison-mk** [comment]
Hi @jkpieterse, thanks for submitting this issue! I've updated the snippet and will close this issue after merging that PR.
