### ISSUE TITLE
Get image from PowerPoint document

### ISSUE THREAD

**Issue by sboudouk** [OfficeDev/office-js-snippets#692]
Hello, thanks for your work and your samples.

I don't know if it's an appropriate spot for my questions but here it is:

How one is supposed to get image from a PowerPoint file ? 

[getSelectedDataSync](url) returns an error when an image is selected. Reading the docs it seems like it is not possible by any of the provided function.

So, is it even possible ?

Thanks :)

**Comment by Rick-Kirkham** [comment]
@sboudouk I'm researching this, but I don't think there's a way to get an image from a slide programmatically.

**Comment by Rick-Kirkham** [comment]
undoing the bot closure

**Comment by Rick-Kirkham** [comment]
bot keeps closing this. I think removing the **Type: programming question** will stop this.

**Comment by Rick-Kirkham** [comment]
@sboudouk I have confirmed that there is no way to get an image from a PowerPoint slide in Office Add-ins. We are beefing up our PowerPoint APIs, but this feature is not yet supported. 

I'll close this issue. Sorry, the news wasn't what you hoped. You might consider looking into the [OOXML SDK](https://docs.microsoft.com/office/open-xml/open-xml-sdk) and see if your scenario can be accomplished with a .NET language in an ASP.NET backend of your add-in.

**Comment by sboudouk** [comment]
Thanks for your answer @Rick-Kirkham . Do you know if is this feature is planned or not at all ?

**Comment by Rick-Kirkham** [comment]
This feature is not currently scheduled, but I have put your request for it to the PowerPoint team. It would be at least a year before it is available.

**Comment by sboudouk** [comment]
Thanks for your help. We'll find another way to achieve something similar, and repost here if I find something that could be useful to someone in the same case.
