### ISSUE TITLE
Reorganize libraries tab

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-js-snippets#81]
Right now the split between JS libraries and their types -- esp. for Office.js reference -- is making it really hard to switch versions.

Reorganizing the libraries.

Will first do this for default template, we can then do it for the rest.

**Comment by kbrandl** [comment]
@Zlatkovsky -- I'll take ownership of this issue (work item).

**Comment by AlexJerabek** [comment]
Fixed with https://github.com/OfficeDev/office-js-snippets/pull/181
