### ISSUE TITLE
loadCustomPropertiesAsync example doesn't work any longer.

### ISSUE THREAD

**Issue by cut2run** [OfficeDev/office-js-snippets#883]
For [loadCustomPropertiesAsync](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-preview#outlook-office-messageread-loadcustompropertiesasync-member(1)) there are two examples in the "Examples" section of the method description. The second example has the issue as of recent change. 
Before the `result.value` of the asynchronous function call was looking as follows...
``` json
{
  rawData: {
    someKey: "someValue",
  },
}
```
And `const dataKey = Object.keys(customProps)[0];` would return correct values of the custom properties bundle (See index 0, which leads to `rawData` key). Recently the returned data has been changed to the following ...
``` json
{
  isLoadedItem: false,
  rawData: {
    someKey: "someValue",
  },
}
```
As you may notice the first item of the object is not `rawData` any longer and the code stopped working. 
This needs to be addressed by using the name of the `rawData` container or even better to use `.getAll()` function which was added at 1.9 level API. The code may look like the following ...

``` TypeScript
    let data = {};
    if (Office.context.requirements.isSetSupported("Mailbox", "1.9")) {
        data = customProps .getAll();
    } else {
        data = customProps ["rawData"];
    }
```

**Comment by samantharamon** [comment]
Hi @cut2run,

Thanks again for reporting this issue and providing a fix. We're including your fix in PR #884. The PR is currently being reviewed. Once we merge the changes, this issue will automatically close. If you have any questions after this issue closes, feel free to create a new issue on GitHub.
